services:
  owl-assistant-api:
    build: .
    container_name: owl-assistant-api
    restart: unless-stopped
    env_file:
      - .env
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
    device_cgroup_rules:
      - "c 189:* rmw"
